#!/usr/bin/env python3
"""Static file server for this directory, HTTP/1.1 with keep-alive so it
behaves correctly behind Caddy's reverse_proxy (the stdlib CLI's default
HTTP/1.0, connection-per-request behavior causes empty replies under Caddy)."""
import sys
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer

class Handler(SimpleHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def end_headers(self):
        # the embeddings files are generated, regenerated by hand, and large
        # (a couple MB) -- a short cache saves re-downloading them on every
        # refresh without risking staleness for long. Everything else
        # (index.html, statements.csv) is actively hand-edited, so it stays
        # fully no-store.
        if self.path.endswith(("embeddings.bin", "embeddings-manifest.json")):
            self.send_header("Cache-Control", "public, max-age=300")
        else:
            self.send_header("Cache-Control", "no-store, no-cache, must-revalidate, max-age=0")
            self.send_header("Pragma", "no-cache")
            self.send_header("Expires", "0")
        super().end_headers()

if __name__ == "__main__":
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8831
    bind = sys.argv[2] if len(sys.argv) > 2 else "127.0.0.1"
    ThreadingHTTPServer.address_family = __import__("socket").AF_INET
    server = ThreadingHTTPServer((bind, port), Handler)
    server.serve_forever()
